FROM golang:1.15-alpine

RUN \
    apk add --no-cache \
    git \
    xz \
    curl \
    entr

# RUN \
#     apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
#     watchexec


# install watchexec
ARG WATCHEXEC_VERSION=1.20.4
RUN curl -sSfL https://github.com/watchexec/watchexec/releases/download/cli-v${WATCHEXEC_VERSION}/watchexec-${WATCHEXEC_VERSION}-$(uname -m)-unknown-linux-gnu.tar.xz | \
    tar -C /usr/local/bin --strip-components 1 -xJ watchexec-${WATCHEXEC_VERSION}-$(uname -m)-unknown-linux-gnu/watchexec && \
	chmod u+x /usr/local/bin/watchexec

WORKDIR /tmp/request-service

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
# RUN CGO_ENABLED=0 go build -o /usr/bin/request-service .

LABEL maintainer="INS"

#CMD watchexec -e go -r go run ./main.go
CMD ls *.go | entr go run ./main.go