# no alpine due to special compilation flags no available on alpine
FROM golang:1.18 AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . ./
ARG SKAFFOLD_GO_GCFLAGS
RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -o /app/request-service .

FROM gcr.io/distroless/base:debug
ENV GOTRACEBACK=single

WORKDIR /app
COPY --from=build /app/request-service /app/request-service

ENTRYPOINT [ "/app/request-service" ]

# CMD find . -type f -name "*.go" | entr -n -r  go run ./main.go
# CMD go run ./main.go