apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: request-service
build:
  artifacts:
  - image: insost/jagw-request-service
    docker:
      dockerfile: Dockerfile_non_compiled.dev
    sync:
      manual:
        - src: '**/*.go'
          dest: .

deploy:
  #statusCheckDeadlineSeconds: 15 # max time to wait for deplyoment to become ready (maybe bug sometimes it takes 2 minutes)
  kubectl:
    defaultNamespace: jagw-dev-dominique
    manifests:
    - kubernetes/request-service-cm.yaml
    - kubernetes/request-service-deploy.yaml
    - kubernetes/request-service-np.yaml
    - kubernetes/request-service-secret.yaml
