// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: graph-db-feeder.proto

package graphdbfeeder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *NodeIds) Reset() {
	*x = NodeIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_db_feeder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIds) ProtoMessage() {}

func (x *NodeIds) ProtoReflect() protoreflect.Message {
	mi := &file_graph_db_feeder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIds.ProtoReflect.Descriptor instead.
func (*NodeIds) Descriptor() ([]byte, []int) {
	return file_graph_db_feeder_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIds) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Asn  int32  `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_db_feeder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graph_db_feeder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graph_db_feeder_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetAsn() int32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

var File_graph_db_feeder_proto protoreflect.FileDescriptor

var file_graph_db_feeder_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x64, 0x62, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x64, 0x62,
	0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x3c, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x73, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x73,
	0x6e, 0x32, 0x4c, 0x0a, 0x0d, 0x47, 0x72, 0x61, 0x70, 0x68, 0x44, 0x62, 0x46, 0x65, 0x65, 0x64,
	0x65, 0x72, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x64, 0x62, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x64, 0x62,
	0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x6a, 0x5a, 0x68, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x73, 0x74, 0x2e, 0x63, 0x68,
	0x2f, 0x69, 0x6e, 0x73, 0x2f, 0x6a, 0x61, 0x6c, 0x61, 0x70, 0x65, 0x6e, 0x6f, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x64, 0x62,
	0x2d, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x64, 0x62,
	0x2d, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x64, 0x62, 0x66, 0x65, 0x65, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_graph_db_feeder_proto_rawDescOnce sync.Once
	file_graph_db_feeder_proto_rawDescData = file_graph_db_feeder_proto_rawDesc
)

func file_graph_db_feeder_proto_rawDescGZIP() []byte {
	file_graph_db_feeder_proto_rawDescOnce.Do(func() {
		file_graph_db_feeder_proto_rawDescData = protoimpl.X.CompressGZIP(file_graph_db_feeder_proto_rawDescData)
	})
	return file_graph_db_feeder_proto_rawDescData
}

var file_graph_db_feeder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_graph_db_feeder_proto_goTypes = []interface{}{
	(*NodeIds)(nil), // 0: graphdbfeeder.NodeIds
	(*Node)(nil),    // 1: graphdbfeeder.Node
}
var file_graph_db_feeder_proto_depIdxs = []int32{
	0, // 0: graphdbfeeder.GraphDbFeeder.GetNodes:input_type -> graphdbfeeder.NodeIds
	1, // 1: graphdbfeeder.GraphDbFeeder.GetNodes:output_type -> graphdbfeeder.Node
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_graph_db_feeder_proto_init() }
func file_graph_db_feeder_proto_init() {
	if File_graph_db_feeder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graph_db_feeder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_db_feeder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graph_db_feeder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_db_feeder_proto_goTypes,
		DependencyIndexes: file_graph_db_feeder_proto_depIdxs,
		MessageInfos:      file_graph_db_feeder_proto_msgTypes,
	}.Build()
	File_graph_db_feeder_proto = out.File
	file_graph_db_feeder_proto_rawDesc = nil
	file_graph_db_feeder_proto_goTypes = nil
	file_graph_db_feeder_proto_depIdxs = nil
}
