---
# Source: jagw/templates/request-service/request-service-np.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: request-service
  name: request-service
spec:
  ports:
  - name: 9000-8080
    port: 8080
    protocol: TCP
    targetPort: 9000
    nodePort: 30061 
  selector:
    app: request-service
  type: NodePort