---
# Source: jagw/templates/request-service/request-service-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "request-service-config"
data:
    SENTINEL_ADDRESS: jagw-redis.jagw-dev-dominique.svc.cluster.local:26379
    SENTINEL_MASTER: mymaster
    APP_SERVER_ADDRESS: 0.0.0.0:9000
    INFLUX_ADDRESS: influxdb.jalapeno.svc.cluster.local:8086
    INFLUX_DB: mdt_db
    LOG_LEVEL: trace