---
# Source: jagw/templates/request-service/request-service-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "request-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "request-service"
  template:
    metadata:
      labels:
        app: "request-service"
    spec:
      containers:
        - image: "insost/jagw-request-service:dev-30"
          ports:
          - containerPort: 9000
            protocol: TCP
          envFrom:
            - configMapRef:
                name: request-service-config
            - secretRef:
                name: request-service-secret
          name: "request-service"
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "1024Mi"
              cpu: "1"